# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # CentOS 6.7
  config.vm.box = "bento/centos-6.7"

  # CentOS 7
  # config.vm.box = "bento/centos-7.1"

  # network
  config.vm.network "private_network", ip:"172.17.8.100"
  config.vm.hostname="redmine.local"

  # synced_folder
  config.vm.synced_folder "./", "/vagrant", disabled: true
  config.vm.synced_folder "../playbook/", "/playbook", :mount_options => ["dmode=775", "fmode=664"]

  # customize
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.provision :shell, :path => "provision.sh"
end
