# install packages for ruby

- name: install packages for ruby
  sudo: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - gcc
    - openssl-devel
    - readline-devel
    - zlib-devel
